### ISSUE TITLE
Create a new test file 'test_read_handling.py`

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1226]
`test_scripts` is getting pretty large and unwieldy; might be time to take all of the tests for interleave-reads, split-paired-reads, and extract-paired-reads and put them in a new file.

**Comment by bocajnotnef** [comment]
I'll handle this.

**Comment by ctb** [comment]
Ripping this from @bocajnotnef's hands and giving it to @ljcohen.

**Comment by ljcohen** [comment]
removed all functions related to interleave-reads, split-paired-reads, and extract-paired-reads and made new file 'test_read_handling.py'

To-do: Figure out how setup.py works. What file should be modified so 'test_read_handling.py' is used for those tests instead of test_scripts.py?

Running ./setup.py with a removed function 'test_interleave_read_seq1_fq', so I know it won't work:

copying build/lib.linux-x86_64-2.7/khmer/_khmer.so -> khmer
Failure: ValueError (No such test test_interleave_read_seq1_fq) ... ERROR

======================================================================
ERROR: Failure: ValueError (No such test test_interleave_read_seq1_fq)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lisa/miniconda/envs/khmer_dev/lib/python2.7/site-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
ValueError: No such test test_interleave_read_seq1_fq

**Comment by luizirber** [comment]
We use [nose][1] to run our tests, and it should autodetect the new file and run the tests.

To run a specific test, you can use
`python setup.py nosetests --tests tests.test_scripts:test_interleave_read_seq1_fq`
you probably want to replace `tests.test_scripts:test_interleave_read_seq1_fq` with `tests.test_read_handling:test_interleave_read_seq1_fq`

[1]: https://nose.readthedocs.org/en/latest/

**Comment by ljcohen** [comment]
worked,thank you! Ran Jenkins and failed 1 tests with `./setup.py nosetests --tests tests.test_scripts:test_load_into_counting_autoargs_0`

>load-into-counting.py: error: argument -U/--unique-kmers: invalid float value: u'1ine7'

**Comment by ljcohen** [comment]
merged #1315
