### ISSUE TITLE
Update docs on setting memory params

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1558]
https://khmer.readthedocs.io/en/latest/user/choosing-table-sizes.html should probably be updated to refer to the new 'unique-kmers.py' script and the -U parameter to load-into-counting that sets memory based on the # of unique kmers.

**Comment by standage** [comment]
Working on this one. I haven't used the `-U` flag before, but based on a brief review of the code and a test on the command line I think I've got the gist. It looks like the flag does not set memory but calculates and reports the estimated FPR before consuming the input data, so that if the FPR is too high you can cancel it before any time is wasted. Is this correct?
