### ISSUE TITLE
Auto cancellation for travis builds

### ISSUE THREAD

**Issue by betatim** [dib-lab/khmer#1662]
https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation

Should we enable that to do our share in being good citizens? I for one use up far too much of travis with "ah, damn it just need to amend that last commit..."

**Comment by standage** [comment]
Definitely. I don't think we're at risk of running up a backlog on pushes (merges) to master, but yeah the n+1s on PRs can pile up. I've even manually gone back cancelled 2+ pending builds a few times so that only the latest would build. I was less motivated by being a good citizen than by getting the builds done more quickly, but hey it's better for everyone!

**Comment by betatim** [comment]
Enabled for PRs.
