### ISSUE TITLE
False positive with exact counting demo

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1683]
Thread #1486 proposed a demo for exact counting via the Python API, which was added in #1658. However, this example produces a false positive, which shouldn't be happening.

```
$ python examples/python-api/exact-counting.py
AAAAAA 2
ATGGCA 2
ACATGG 1
GGGGGT 2
```

This last k-mer was never consumed by the countgraph.

**Comment by betatim** [comment]
Can reproduce this with:
```
In [18]: cg = khmer.Countgraph(ksize, nkmers, 1)

In [19]: for i in range(nkmers):
    ...:     if cg.get(i):
    ...:         kmer = cg.reverse_hash(i)
    ...:         print(kmer, cg.get(i), cg.hash(kmer))
    ...:         

In [20]: cg.count('AAAAAA')
Out[20]: 1

In [21]: for i in range(nkmers):
    ...:     if cg.get(i):
    ...:         kmer = cg.reverse_hash(i)
    ...:         print(kmer, cg.get(i), cg.hash(kmer))
    ...:         
AAAAAA 1 0
GGGGGT 1 682
```

**Comment by betatim** [comment]
`nkmers = 4096`, but the nearest prime is 4093 (`cg.get_raw_tables()[0].shape == (4093,)`) so this is the result of having to take the modulus.
```python
In [22]: for i in range(nkmers):
    ...:     if cg.get(i):
    ...:         kmer = cg.reverse_hash(i)
    ...:         print("%04i"%i, kmer, cg.get(i), cg.get(kmer), cg.hash(kmer))
    ...:         
    ...:         
0000 AAAAAA 1 1 0
4093 GGGGGT 1 1 682
```

if you pass an integer to `cg.get` it interprets it as hash value, which is use directly to index into the table, which in this case wraps around due to the modulus operation. So you get the count for "AAAAAA" despite the reverse of the hash being something different.

If you pick a prime > 4096 the problem goes away:
```python
In [45]: cg2 = khmer._Countgraph(ksize, [4099])

In [46]: cg2.count('AAAAAA')
Out[46]: 1

In [47]: for i in range(nkmers):
    ...:     if cg2.get(i):
    ...:         kmer = cg2.reverse_hash(i)
    ...:         print("%04i"%i, kmer, cg2.get(i), cg2.get(kmer), cg2.hash(kmer)
    ...: )
    ...:         
    ...:         
0000 AAAAAA 1 1 0
```

(and the problem returns if you loop over `range(4099+1)`.)

**Comment by betatim** [comment]
Not sure what we could do to make this behaviour less surprising. Make `cg.reverse_hash` fold hash values over like the table does?? Then you'd probably be confused why different hash values give you the same kmer string ... :-/

**Comment by standage** [comment]
Ok, I understand what's going on. The data structure is doing the right thing. See latest changes to #1658. This issue is solved and will be closed when that PR is merged.
