### ISSUE TITLE
Docker CI build broken

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1777]
The latest merge seems to have broken @mr-c's latest contributions for Docker builds in Travis (#1333). See https://travis-ci.org/dib-lab/khmer/jobs/272705892.

**Comment by betatim** [comment]
I think the problem is that [`make docker-container`](https://github.com/dib-lab/khmer/blob/master/Makefile#L394) uses TRAVIS_PULL_REQUEST_SHA which is empty when we are building master. From https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables my guess would be that TRAVIS_COMMIT is always available (and set).
