### ISSUE TITLE
Revisit PR checklist

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1822]
Our PR checklist is pretty heavyweight right now, and is routinely ignored by PR submitters. I too often find myself deleting or <strike>crossing out</strike> many of the checklist items.

If the checklist is going to be ignored, then it's worse than useless. Do we need to trim it down to make it less tedious? Should we be stricter about enforcing checklist completion before code review? I'm +1 on both.

**Comment by betatim** [comment]
One more option would be to automate some of the checks as a way to "enforcing" them.

I'm becoming a fan of the way codecov and pep8speaks make one comment and then update it. I think that works better than having travis fail because we can decide that "no for this PR it is Ok to reduce coverage" or some such.
