### ISSUE TITLE
k-mer counts by position/nucleotide coverage

### ISSUE THREAD

**Issue by blue-moon22** [dib-lab/khmer#1893]
Hi there,

I have a metagenome file and would like to compute the k-mer counts for each position on every read. In other words, the nucleotide coverage. I saw something promising in the "Illumina read abundance profile" section: https://khmer.readthedocs.io/en/latest/user/blog-posts.html but the scripts are no longer available in current version of sandbox.

Do you have any scripts that could do this?

Best,
Vicky

**Comment by standage** [comment]
Hi Vicky,

The scripts you reference were removed in #1358. If you want to see what they looked like at the time, you can find them [here](https://github.com/dib-lab/khmer/tree/ff7f047b5b0d9acb6c1eb73d54cfd39c9e3d1393/sandbox). It looks like they were removed since they were rarely used, and I'm not sure if the current API supports them any more. 😕

**Comment by blue-moon22** [comment]
No they don't support them. Do you know when this blog was written and at what version/commit of API? These functions would be really useful for me!

**Comment by standage** [comment]
You can check out the ff7f047b5b0d9acb6c1eb73d54cfd39c9e3d1393 commit (which corresponds to the second link I provided) and try to build khmer from that commit. However, there's a chance that the scripts might already have been out of sync with the API by then. You might have to revert to an even earlier version of the repo to get to a point where the scripts work with the API.

**Comment by blue-moon22** [comment]
Sorted! Thanks
