### ISSUE TITLE
pylint complains too much about tests/

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#326]
We should disable some of the pylint warnings just for the tests.

1686 warnings right now

Candidates:

C0103: Invalid constant name (789 warnings)
C0111: Missing module docstring (360 warnings)
E1101: missing member (319 warnings: due to pylint not being able to introspect the khmer module)
R0201: method could be a function  (23 warnings)
W0212: Access to a protected member of a client class (25 warnings)

**Comment by moorepants** [comment]
I'll see about this one.

**Comment by bocajnotnef** [comment]
+1 for disabling much of these warnings

**Comment by standage** [comment]
@betatim It looks like pylint is being run on all Travis builds. Should we go ahead and close this thread as wontfix?

**Comment by betatim** [comment]
We run pylint but the build won't fail if pylint is unhappy.

In its current state the output of `pylint tests/*py` is not so useful because it outputs a lot. `make diff_pylint_report` is more useful. Not sure I have an opinion on disabling checks, a lot of good practices don't apply to tests because you want to do weird stuff ...

Conclusion: do what you think is best, I am +-0 on everything ;)

**Comment by standage** [comment]
@betatim Yeah I'll just leave this open for now, but not giving it any kind of priority.
