### ISSUE TITLE
split-paired-reads.py has nonstandard behavior with orphaned reads

### ISSUE THREAD

**Issue by camillescott** [dib-lab/khmer#847]
By default, split-paired-reads.py mixes orphaned reads into their respective .1 / .2 files, which is a nonstandard behavior -- orphaned reads should be put into their own files. Tools like bowtie and Trinity fail when they encounter orphaned reads mixed into split paired files.

**Comment by ctb** [comment]
We talked about this in person, and the conclusion was that we cannot alter this until khmer 2.0; but the -p was added in #818 to force the expected behavior.

Two thoughts -

1. shall we update the documentation to make this clear?
2. @mr-c, what's the right way to punt these kinds of issues to khmer 2.0 release?

**Comment by ctb** [comment]
For 2.0,

- [ ] make -p default;
- [ ] upgrade extract-paired-reads to properly handle streaming input and specification of output files;
- [ ] in the error message that results from -p, mention that extract-paired-reads can be used to fix;

@camillescott @mr-c the alternative here is to add an option to split-paired-reads to sideline or trash orphans. I think this makes the script too complicated so am -0 on it but would appreciate your thoughts.

**Comment by ctb** [comment]
Closed by #1164.
